application:
  name: echo-boilerplate
  version: 0.0.1
  port: 8888
  cors:
    allowedHost: localhost, https://labstack.com, https://labstack.net

db.configs:
  username: root
  password:
  host: localhost
  port: 3306
  database: test_ent

outbound:
  quotes:
    get-url: https://programming-quotesapi.vercel.app/api/random
    post-url: https://en8trqq30hty3.x.pipedream.net/


