application:
  name: echo-boilerplate
  version: 0.0.1
  port: 8888
  cors:
    allowedHost: localhost, https://labstack.com, https://labstack.net

db.configs:
  username: root
  password:
  host: localhost
  port: 3306
  database: test_ent

